package publications

import publications.data.local.publicationsLocalDataModule
import publications.data.repository.publicationsRepositoryDataModule
import publications.domain.publicationsDomainModule

val publicationsModule = publicationsRepositoryDataModule + publicationsLocalDataModule + publicationsDomainModule